pipeline{
    agent any

    stages {
        stage('Fetch Code') {
            when {
                changeset "**/Src/FrontEnd/Gateway/PaymentGateway.GatewayUi/**"  // Only trigger when files in the 'src' folder change
            }
            steps {
                git url: 'git@github.com:eshghi26/paygate.git',
                branch: 'main',
                credentialsId: 'mygitubpk'
            }
        }

        stage('Build Docker Image'){
            when {
                changeset "**/Src/FrontEnd/Gateway/PaymentGateway.GatewayUi/**"  // Only trigger when files in the 'src' folder change
            }
            steps {
                script {
                    dockerImage = docker.build("payui:V$BUILD_NUMBER", "-f Src/FrontEnd/Gateway/PaymentGateway.GatewayUi/Dockerfile .")
                }
            }
        }


        stage('Deploy') {
            when {
                changeset "**/Src/FrontEnd/Gateway/PaymentGateway.GatewayUi/**"  // Only trigger when files in the 'src' folder change
            }
            steps {
                sh "docker run -dp 0.0.0.0:6060:8080 payui:V$BUILD_NUMBER"
            }
        }
    }

}
