services:
  postgresdb:
    image: postgres

  redisDb:
    image: redis:alpine

  elasticsearch:
    image: elasticsearch:8.15.3

  kibana:
    image: kibana:8.15.3

  paymentgateway.api:
    image: ${DOCKER_REGISTRY-}paymentgatewayapi
    build:
      context: .
      dockerfile: Src/Backend/PaymentGateway.Api/Dockerfile

  paymentgateway.paymentapi:
    image: ${DOCKER_REGISTRY-}paymentgatewaypaymentapi
    build:
      context: .
      dockerfile: Src/Backend/PaymentGateway.PaymentApi/Dockerfile

  paymentgateway.gatewayui:
    image: ${DOCKER_REGISTRY-}paymentgatewaygatewayui
    build:
      context: .
      dockerfile: Src/FrontEnd/Gateway/PaymentGateway.GatewayUi/Dockerfile

networks:
  elastic:
    driver: bridge


volumes:
  postgresdb_data:
  esdata: