services:
  postgresdb:
    image: postgres

  redisDb:
    image: redis:alpine

  paymentgateway.api:
    image: ${DOCKER_REGISTRY-}paymentgatewayapi
    build:
      context: .
      dockerfile: Src/Backend/PaymentGateway.Api/Dockerfile

  paymentgateway.paymentapi:
    image: ${DOCKER_REGISTRY-}paymentgatewaypaymentapi
    build:
      context: .
      dockerfile: Src/Backend/PaymentGateway.PaymentApi/Dockerfile

  paymentgateway.gatewayui:
    image: ${DOCKER_REGISTRY-}paymentgatewaygatewayui
    build:
      context: .
      dockerfile: Src/FrontEnd/Gateway/PaymentGateway.GatewayUi/Dockerfile

volumes:
  postgresdb_data:

